### PR TITLE
Add support for gulpfile.babel.js and test

### PR DESCRIPTION
**Pull request by flying-sheep**
there’s a problem: to test `gulpfile.js`, you need gulp v3 installed, to test `gulpfile.babel.js`, you need gulp v4 installed.

seem like your tests aren’t working at all.

PS: if you want to test gulpfile.babel.js, you also need `babel-register` and `babel-plugin-transform-es2015-modules-commonjs`

### CODE REVIEW

**Comment by nealoke** [comment]
+1 for this #13

**Comment by flying-sheep** [comment]
OK, so turns out the code actually expects strings for the glob patterns, not arrays.

- i adapted the settings accordingly in 89de4d2250f566f3dd1b08e0c77b04272e8a680b
- `path.relative` can return `""`, but the code only checks `if (result.relativePath != null)`. this is a problem because plain `cd` is the same as `cd ~`. so i made sure `relativePath` is never empty cb9487f0809ab318e6eb8629b4a2237ad7b1758e

**Comment by lkytal** [comment]
Thanks.

**Comment by flying-sheep** [comment]
no problem! but you should make sure that your tests run!

i get errors in some of them (unrelated to my changes)

**Pull request merged**
